### GENERAL SETTINGS ###

# Site settings
title: SVS
description:
baseurl: "" #important: start with /
url:

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: http://www.github.com/soumyavardhan
#  - title: facebook
#    url:
  - title: twitter
    url: http://www.twitter.com/soumyavardhan
#  - title: instagram
#    url: 
  - title: linkedin
    url: http://in.linkedin.com/pub/soumya-vardhan-singh/37/141/b84
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
#address:
#  - lines: 
#    
#email:
#tel:


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
#members:
#  - name: xyz
#    position: abc
#    text: jghsdfjhgsdf
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
    
# Clients information. Shown on Home and About pages.
#clients:
#  - name:
#    img:
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Soumya Vardhan Singh"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "I made this website to remind myself why I do what I do in the first place."
    author: Soumya Vardhan Singh
    position:
